import { ListPageType } from 'Types/Types';

export const test: ListPageType = [
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: [
      '수학',
      '국어',
      'sdfadsfadsfs',
      '한국사',
      '영어',
      '과학',
      '사회',
      '한국사',
    ],
    area: ['서울', '경기', '대전', '강원', '경기', '대전', '강원'],
    classMethod: {
      onLine: true,
      offLine: false,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['수학', '국어', '과학'],
    area: ['서울', '경기'],
    classMethod: {
      onLine: true,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: [
      '수학',
      '국어',
      'sdfadsfadsfs',
      '한국사',
      '영어',
      '과학',
      '사회',
      '한국사',
    ],
    area: ['서울', '경기', '대전', '강원', '경기', '대전', '강원'],
    classMethod: {
      onLine: true,
      offLine: false,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['수학', '국어', '과학'],
    area: ['서울', '경기'],
    classMethod: {
      onLine: true,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: [
      '수학',
      '국어',
      'sdfadsfadsfs',
      '한국사',
      '영어',
      '과학',
      '사회',
      '한국사',
    ],
    area: ['서울', '경기', '대전', '강원', '경기', '대전', '강원'],
    classMethod: {
      onLine: true,
      offLine: false,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['수학', '국어', '과학'],
    area: ['서울', '경기'],
    classMethod: {
      onLine: true,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: [
      '수학',
      '국어',
      'sdfadsfadsfs',
      '한국사',
      '영어',
      '과학',
      '사회',
      '한국사',
    ],
    area: ['서울', '경기', '대전', '강원', '경기', '대전', '강원'],
    classMethod: {
      onLine: true,
      offLine: false,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['수학', '국어', '과학'],
    area: ['서울', '경기'],
    classMethod: {
      onLine: true,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: [
      '수학',
      '국어',
      'sdfadsfadsfs',
      '한국사',
      '영어',
      '과학',
      '사회',
      '한국사',
    ],
    area: ['서울', '경기', '대전', '강원', '경기', '대전', '강원'],
    classMethod: {
      onLine: true,
      offLine: false,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['수학', '국어', '과학'],
    area: ['서울', '경기'],
    classMethod: {
      onLine: true,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: [
      '수학',
      '국어',
      'sdfadsfadsfs',
      '한국사',
      '영어',
      '과학',
      '사회',
      '한국사',
    ],
    area: ['서울', '경기', '대전', '강원', '경기', '대전', '강원'],
    classMethod: {
      onLine: true,
      offLine: false,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['수학', '국어', '과학'],
    area: ['서울', '경기'],
    classMethod: {
      onLine: true,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
  {
    img: 'https://png.pngtree.com/png-clipart/20220113/ourlarge/pngtree-cartoon-hand-drawn-default-avatar-png-image_4156500.png',
    name: '조상옥',
    category: ['영어', '과학'],
    area: ['서울', '경기', '강원'],
    classMethod: {
      onLine: false,
      offLine: true,
    },
  },
];
