import React from 'react';

const TeacherCard = () => {
  return (
    <>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
      <div>TeacherCard</div>
    </>
  );
};

export default TeacherCard;
